sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 121.40.118.178
    port: 3306
    database: sky_take_out
    username: baroot
    password: Baroot@456qaz
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tBQhhUiXNUgndnjT8me
    access-key-secret: WFGe6Mmjtq3tqhrjOQH8Or2W5Tc3dm
    bucket-name: ericjohnson
